export * from "./setting";
export * from "./home";
export * from "./about";
export * from "./news";
export * from "./utils";
export * from "./address";
export * from "./product";
export * from "./contact";
export * from "./cart";
